name: Deploy frontend
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - run:  docker build -t shoaibakhtar1010/react-test -f Dockerfile.dev
      - run:  docker run -e CI=true shoaibakhtar1010/react-test npm test

      - name: generate deployment package
        run:  zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: dockerapp2
          environment_name: Dockerapp2-env
          existing_bucket_name: elasticbeanstalk-us-east-1-076508345739
          version_label:  ${{github.sha}}
          region: us-east-1
          deployment_package: deploy.zip